import colors from './colors';

const {
  inclusivePride,
  gilbertBakerPride,
  trans,
  bisexual,
  pan,
  polysexual,
  asexual,
  nonbinary,
  genderqueer,
  genderfluid,
  agender,
  aromantic
} = colors;

export default {
  inclusivePride: [
    inclusivePride.black,
    inclusivePride.brown,
    inclusivePride.red,
    inclusivePride.orange,
    inclusivePride.yellow,
    inclusivePride.green,
    inclusivePride.blue,
    inclusivePride.purple,
  ],
  pride: [
    inclusivePride.red,
    inclusivePride.orange,
    inclusivePride.yellow,
    inclusivePride.green,
    inclusivePride.blue,
    inclusivePride.purple,
  ],
  gilbertBakerPride: [
    gilbertBakerPride.hotPink,
    gilbertBakerPride.red,
    gilbertBakerPride.orange,
    gilbertBakerPride.yellow,
    gilbertBakerPride.green,
    gilbertBakerPride.turquoise,
    gilbertBakerPride.indigo,
    gilbertBakerPride.violet,
  ],
  pride1978: [
    gilbertBakerPride.red,
    gilbertBakerPride.orange,
    gilbertBakerPride.yellow,
    gilbertBakerPride.green,
    gilbertBakerPride.turquoise,
    gilbertBakerPride.indigo,
    gilbertBakerPride.violet,
  ],
  trans: [
    trans.blue,
    trans.pink,
    trans.white,
    trans.pink,
    trans.blue,
  ],
  bisexual: [
    bisexual.pink,
    bisexual.purple,
    bisexual.blue,
  ],
  pan: [
    pan.pink,
    pan.pink,
    pan.yellow,
    pan.yellow,
    pan.blue,
    pan.blue,
  ],
  polysexual: [
    polysexual.pink,
    polysexual.pink,
    polysexual.green,
    polysexual.green,
    polysexual.blue,
    polysexual.blue,
  ],
  asexual: [
    asexual.black,
    asexual.black,
    asexual.grey,
    asexual.grey,
    asexual.white,
    asexual.white,
    asexual.purple,
    asexual.purple,
  ],
  nonbinary: [
    nonbinary.black,
    nonbinary.black,
    nonbinary.yellow,
    nonbinary.yellow,
    nonbinary.white,
    nonbinary.white,
    nonbinary.purple,
    nonbinary.purple,
    nonbinary.black,
    nonbinary.black,
  ],
  genderqueer: [
    genderqueer.purple,
    genderqueer.purple,
    genderqueer.white,
    genderqueer.white,
    genderqueer.green,
    genderqueer.green,
  ],
  genderfluid: [
    genderfluid.pink,
    genderfluid.pink,
    genderfluid.white,
    genderfluid.white,
    genderfluid.purple,
    genderfluid.purple,
    genderfluid.black,
    genderfluid.black,
    genderfluid.blue,
    genderfluid.blue,
  ],
  agender: [
    agender.black,
    agender.grey,
    agender.white,
    agender.green,
    agender.white,
    agender.grey,
    agender.black,
  ],
  aromantic: [
    aromantic.darkGreen,
    aromantic.lightGreen,
    aromantic.white,
    aromantic.grey,
    aromantic.black,
  ]
};
