import colors from './colors';

export default {
  inclusivePride: [
    colors.inclusivePride.black,
    colors.inclusivePride.brown,
    colors.inclusivePride.red,
    colors.inclusivePride.orange,
    colors.inclusivePride.yellow,
    colors.inclusivePride.green,
    colors.inclusivePride.blue,
    colors.inclusivePride.purple,
  ],
  pride: [
    colors.inclusivePride.red,
    colors.inclusivePride.orange,
    colors.inclusivePride.yellow,
    colors.inclusivePride.green,
    colors.inclusivePride.blue,
    colors.inclusivePride.purple,
  ],
  trans: [
    colors.trans.blue,
    colors.trans.pink,
    colors.trans.white,
    colors.trans.pink,
    colors.trans.blue,
  ],
  bisexual: [
    colors.bisexual.pink,
    colors.bisexual.purple,
    colors.bisexual.blue,
  ],
  pan: [
    colors.pan.pink,
    colors.pan.pink,
    colors.pan.yellow,
    colors.pan.yellow,
    colors.pan.blue,
    colors.pan.blue,
  ],
  polysexual: [
    colors.polysexual.pink,
    colors.polysexual.pink,
    colors.polysexual.green,
    colors.polysexual.green,
    colors.polysexual.blue,
    colors.polysexual.blue,
  ],
  asexual: [
    colors.asexual.black,
    colors.asexual.black,
    colors.asexual.grey,
    colors.asexual.grey,
    colors.asexual.white,
    colors.asexual.white,
    colors.asexual.purple,
    colors.asexual.purple,
  ],
  nonbinary: [
    colors.nonbinary.black,
    colors.nonbinary.black,
    colors.nonbinary.yellow,
    colors.nonbinary.yellow,
    colors.nonbinary.white,
    colors.nonbinary.white,
    colors.nonbinary.purple,
    colors.nonbinary.purple,
    colors.nonbinary.black,
    colors.nonbinary.black,
  ],
  genderqueer: [
    colors.genderqueer.purple,
    colors.genderqueer.purple,
    colors.genderqueer.white,
    colors.genderqueer.white,
    colors.genderqueer.green,
    colors.genderqueer.green,
  ],
  genderfluid: [
    colors.genderfluid.pink,
    colors.genderfluid.pink,
    colors.genderfluid.white,
    colors.genderfluid.white,
    colors.genderfluid.purple,
    colors.genderfluid.purple,
    colors.genderfluid.black,
    colors.genderfluid.black,
    colors.genderfluid.blue,
    colors.genderfluid.blue,
  ],
};
